name: Publish newman reporter to npmjs
on: 
  workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/newman-reporter-testomatio
    steps:
      - run: echo ${{ secrets.NPM_TOKEN }}
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
